function [Dz,Dxy,uDC] = denoise_albedo( u, lxs,lys,lzs, denoise_factor, lambda_pu,...
                                        lambda_RMSE, pxo, pyo, pzo, sxo,syo, szo,...
                                        ws, nno, sparse_value, sparse_threshold,...
                                        lambda_xyz_o, threshold_3D_o)
u = reshape(u,lxs,lys,lzs,3);
noisy_img = sqrt( u(:,:,:,1).^2 + u(:,:,:,2).^2 + u(:,:,:,3).^2 );
[Dz,Dxy,denoised_img] = eat_vec( noisy_img, denoise_factor, lambda_pu,...
                                 lambda_RMSE, pxo, pyo, pzo, sxo,syo, szo,...
                                 ws, nno, sparse_value, sparse_threshold,...
                                 lambda_xyz_o, threshold_3D_o);
uDC = repmat(denoised_img,1,1,1,3) .* u ./ repmat(noisy_img,1,1,1,3);
uDC = reshape(uDC,lxs * lys * lzs,3);
uDC(isnan(uDC) == 1) = 0;
end